# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link_01
  pid: {p: 2000.0, i: 100, d: 500.0}

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_01__link_02
  pid: {p: 50000.0, i: 100, d: 2000.0}

joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_01__link_02_2
  pid: {p: 2000.0, i: 100, d: 500.0}

joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_02__link_03
  pid: {p: 50000.0, i: 100, d: 2000.0}

joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_02_2__link_03_3
  pid: {p: 2000.0, i: 100, d: 500.0}

joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_03__link_04
  pid: {p: 50000.0, i: 100, d: 2000.0}

joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_03_3__link_04_4
  pid: {p: 2000.0, i: 100, d: 500.0}

joint8_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_04_4__link_05_55
  pid: {p: 50000.0, i: 100, d: 2000.0}

joint9_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_04_4__link_05_555
  pid: {p: 2000.0, i: 100, d: 500.0}

joint10_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_04__link_05
  pid: {p: 50000.0, i: 100, d: 2000.0} 

joint11_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_04__link_05_5
  pid: {p: 2000.0, i: 100, d: 500.0}



